services:
  log-courier:
    build:
      context: .
      dockerfile: images/svc-base/Dockerfile
    image: ${LOG_COURIER_IMAGE:-log-courier:local}
    container_name: log-courier
    network_mode: host
    profiles:
      - full
    environment:
      SUPERVISORD_CONF: supervisord.conf
    volumes:
      - ./deployment/conf/supervisord.conf:/conf/supervisord.conf:ro
      - ./deployment/conf/env:/conf/env:ro

