global:
  log_level: info

features:
  access_logging:
    enabled: true

cloudserver:
  image: ghcr.io/scality/cloudserver:9.2.14

vault:
  image: ghcr.io/scality/vault:7.83.0

s3_metadata:
  image: ghcr.io/scality/metadata:9.0.0-standalone

clickhouse:
  image: clickhouse/clickhouse-server:24.3.2.23-alpine

fluentbit:
  image: fluent/fluent-bit:3.2.2
