---
name: release-debug
run-name: release-debug ${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be released (will be suffixed with -debug)'
        required: true

jobs:
  build-debug-image:
    uses: ./.github/workflows/build-debug-image.yaml
    with:
      tag: ${{ inputs.tag }}
