---
name: release
run-name: release ${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be released'
        required: true
      build_debug:
        description: 'Also build debug image'
        type: boolean
        default: false
        required: false

jobs:
  build-image:
    uses: ./.github/workflows/build-image.yaml
    with:
      tag: ${{ inputs.tag }}

  build-debug-image:
    if: ${{ inputs.build_debug }}
    uses: ./.github/workflows/build-debug-image.yaml
    with:
      tag: ${{ inputs.tag }}

  release:
    runs-on: ubuntu-latest
    needs:
    - build-image
    - build-debug-image
    steps:
    - name: Create Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Release ${{ github.event.inputs.tag }}
        tag_name: ${{ github.event.inputs.tag }}
        generate_release_notes: true
        target_commitish: ${{ github.sha }}
